version: "3.1"
services:
    webserver:
      image: nginx:alpine
      container_name: phppleno-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./container/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: phppleno-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./container/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
